import { type NextPage } from "next";
import Head from "next/head";
import Card from "~/components/Card";
import ThemeToggle from "~/components/ThemeSwitch";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Theme Toggle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-neutral-100 dark:bg-neutral-900">
        <ThemeToggle />
        <Card />
      </main>
    </>
  );
};

export default Home;
